[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
evm_version = "cancun"
via-ir = true
bytecode_hash = "none"

#[fuzz]
#runs = 50000 # From Crab: I have a beefy Ryzen 9 so idgaf about the overhead :)

[soldeer]
remappings_version = false
remappings_location = "txt"

[dependencies]
forge-std = "1.9.4"
solady = "0.0.273"
"@openzeppelin-contracts" = "5.1.0-rc.0"
"@solidstate-contracts" = "0.0.60"
"@layerzerolabs-oft-evm" = "3.0.0"
